module.exports = {
    name: "aiimage",
    async execute(sock, msg, args) {
        const q = args.join(" ");
        if (!q) return sock.sendMessage(msg.key.remoteJid, { text: "What should I draw, blood?" });
        const url = `https://api.shizuka.site/dalle?prompt=${encodeURIComponent(q)}`;
        await sock.sendMessage(msg.key.remoteJid, { image: { url }, caption: `🎨 *AI ART:* ${q}\n\n_Generated by STANYTZ AI Core_` });
    }
};
